### ISSUE TITLE
Home task (Task 1)

### ISSUE THREAD

**Issue by Shpikls** [Shpikls/ReactJS-GMP#1]
Create components

Switch to a new branch. Create several components using:  

- [x] React.createElement
- [x] React.Component
- [x] React.PureComponent
- [x] Functional component

To understand more how components work it's recommended to create a couple of interactive components, for example:

- [x] A counter, which renders a numeric value and two buttons to increment or decrement the value.
- [x] A search form as per the design guide, which renders a search input and a button to initiate a new search action.
- [x] A genre toggle as per the design guide.

Evaluation criteria* 

- [x] 2 - Install blank create-react-app application; 
- [x] 3 - Render blank message (Hello World) with React; 
- [x] 4 - Use at least 2 methods of creating react components; 
- [x] 5 - Use all methods which mentioned in task, to create React components, install and use all extensions.

**Comment by Shpikls** [comment]
- [ ] create pull request
- [ ] get metors github account
- [ ] add mentors to collaborators repository

**Comment by Shpikls2** [comment]
Add me to check your homework

**Comment by 000000armor** [comment]
Add me to check your homework

**Comment by Shpikls** [comment]
Домашнее задание проверено
